#fargedemo: fargedemo.c fargeskrift.c fargeskrift.h
#	gcc -O2 -o fargedemo fargedemo.c fargeskrift.c

#fargetest: fargetest.c fargeskrift.c fargeskrift.h
#	gcc -O2 -o fargetest fargetest.c fargeskrift.c

hellofarge: hellofarge.c fargeskrift.c fargeskrift.h
	gcc -O2 -o hellofarge hellofarge.c fargeskrift.c
